version: '3.9'

services:
  rabbitmq:
    container_name: rabbitmq-test
    build: 
      context: .
      dockerfile: rabbitmq.Dockerfile
    hostname: rabbitmq-test
    environment:  
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error,info},{default,error,info}] disk_free_limit 2147483648
    ports:
      - 15672:15672
      - 5672:5672
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    restart: on-failure
  
